modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Wawla/issues"
license="LGPL v2.1"

[[mods]]
modId="wawla"
updateJSONURL="https://updates.blamejared.com/get?n=wawla&gv=1.16.5"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.wawla]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.wawla]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="SERVER"

[[dependencies.wawla]]
    modId="bookshelf"
    mandatory=true
    versionRange="[10,)"
    ordering="AFTER"
    side="SERVER"
	
[[dependencies.wawla]]
    modId="waila"
    mandatory=true
    versionRange="[0,)"
    ordering="AFTER"
    side="SERVER"